---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sergey.
--- DateTime: 31/05/2021 14:14
---

local DEBUG_MODE = "DEBUG"
local PROD_MODE = "PROD"

RUN_MODE = DEBUG_MODE
WORKING_DIRECTORY = getScriptPath()

package.cpath = package.cpath .. ";" .. WORKING_DIRECTORY .. "\\?.dll;C:\\Users\\Sergey\\CLionProjects\\quik-connector\\cmake-build-release\\quik_connector.dll"

require("quik_connector")

--[[function main() 
    while (true) do
        if OnStop == nil then
            message('No OnStop')
        else
            message('Exists OnStop')
        end
    
        sleep(10000)
    end
end]]--
