log:
  level: INFO # DEBUG | INFO | WARN | ERROR
  path: logs
  name: quik-connector.log
  max:
    size: 1 # Max file size in Mb
    files: 5 # Rotate max files

redis:
  host: 127.0.0.1
  port: 6379
  password: c1bef278c2eb3d4e16c51148

db:
  path: db
  name: stocks.db
  migrations:
    path: migrations

quik:
  callback:
    enabled:
      all-trade: true
      quote: true
      order: true
      trans-reply: true
  order:
    ignore:
      canceled: true # Remove canceled orders from the list
    save: true # Save all orders to DB
  news:
    file:
      name: news.log
    monitor:
      enabled: true # Check news file for updates and send it to queue

debug:
  print:
    lua-stack: false
