log:
  level: INFO # DEBUG | INFO | WARN | ERROR
  path: logs
  name: quik-connector.log
  max:
    size: 1 # Max file size in Mb
    files: 5 # Rotate max files

redis:
  host: 127.0.0.1
  port: 6379

order:
  ignore:
    canceled: true # Remove canceled orders from the list

db:
  path: db
  name: stocks.db
  migrations:
    path: migrations

debug:
  print:
    lua-stack: true
